/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Run
         * @description Create a new run row, roll a starter party, return RunState.
         *
         *     THEME topics: the player picks a ``theme`` at run start; each battle draws a
         *     random topic within it (resolved at encounter creation). ``debate_topic``
         *     stays populated (NOT NULL) — when a theme is given but no explicit topic, we
         *     label it with the theme so existing readers (runs.py, RunState) never break.
         */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Map
         * @description Return deterministic tile grid + current player pos + wild enemy positions.
         */
        get: operations["get_map_api_runs__run_id__map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move Player
         * @description Move player by (dx,dy); check walkability and wild-enemy collision.
         */
        post: operations["move_player_api_runs__run_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/rest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rest
         * @description Campsite rest: fully heal the party, advance the day, reset encounters.
         *
         *     Healing sets every player-owned monster's effective HP to ``max_hp``. Live HP
         *     is not a column on the frozen ``Monster`` model (battles track HP elsewhere),
         *     so "healed to full" is reflected by returning each party member at ``max_hp``
         *     via MonsterSummary. The day / encounters_since_rest counters are persisted
         *     best-effort (optional columns) and otherwise computed.
         */
        post: operations["rest_api_runs__run_id__rest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Encounter */
        post: operations["create_encounter_api_encounters__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Encounter */
        post: operations["create_encounter_api_encounters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Encounter */
        get: operations["get_encounter_api_encounters__eid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{eid}/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take Turn */
        post: operations["take_turn_api_encounters__eid__turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{eid}/auto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auto */
        post: operations["auto_api_encounters__eid__auto_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{eid}/argue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Argue
         * @description Human-argues (WS-G): the player's typed argument is the lead party monster's
         *     turn; the lead enemy rebuts autonomously. REST fallback for the WS argue action.
         */
        post: operations["argue_api_encounters__eid__argue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{eid}/assist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assist
         * @description ARGUE COPILOT (player-first pivot): the lead party monster COACHES the
         *     player's drafted argument into a stronger one.
         *
         *     This does NOT advance the round — it only suggests. The player then sends the
         *     improved text via the existing POST /{eid}/argue. The coach's quality is driven
         *     by the monster's TRAINED genome, so training the monster improves the help.
         *
         *     404 if the encounter is missing. Wrapped in the same wall-clock guard as
         *     /argue; on timeout or any failure the coach degrades gracefully rather than
         *     500-ing.
         */
        post: operations["assist_api_encounters__eid__assist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{eid}/flee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Flee */
        post: operations["flee_api_encounters__eid__flee_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monsters/{monster_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Monster
         * @description Return basic monster info (used by GambitEditor + BattleDebateView).
         */
        get: operations["get_monster_api_monsters__monster_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monsters/{monster_id}/gambits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Gambits
         * @description Return all gambit rules for a monster, sorted by priority ascending.
         */
        get: operations["get_gambits_api_monsters__monster_id__gambits_get"];
        /**
         * Put Gambits
         * @description Full-replace the gambit list for a monster.
         *
         *     Deletes all existing rules then inserts the provided list in order.
         *     The frontend editor sends the full ordered list; server assigns new UUIDs
         *     for rules that don't have an id yet.
         */
        put: operations["put_gambits_api_monsters__monster_id__gambits_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monsters/{monster_id}/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Memories
         * @description Retrieve memories for a monster using hybrid RAG (vector + trigram).
         *
         *     Query params:
         *         q:    Natural language query (optional; if absent, returns recent memories).
         *         type: Event type filter: BATTLE | PLAYER | CHARACTER (optional).
         *         k:    Max results (default 8).
         */
        get: operations["get_memories_api_monsters__monster_id__memories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/party": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all player-owned monsters in a run
         * @description Return all monsters with owner='player' belonging to the given run.
         */
        get: operations["get_party_api_runs__run_id__party_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monsters/{monster_id}/train/gepa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Train Gepa */
        post: operations["train_gepa_api_monsters__monster_id__train_gepa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monsters/{monster_id}/train/grpo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Train Grpo */
        post: operations["train_grpo_api_monsters__monster_id__train_grpo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/{job_id}/preference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Preference */
        post: operations["submit_preference_api_training__job_id__preference_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_training__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monsters/{monster_id}/training/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Training History
         * @description Legible training timeline for a monster, one entry per TrainingArtifact.
         *
         *     Each artifact records a before/after genome + score_delta + accepted flag. We
         *     surface them oldest-first so the frontend can render an improvement curve. The
         *     artifact schema has no genome_version column, so we reconstruct a monotonic
         *     version label by counting *accepted* artifacts up to each row (matching how
         *     ``apply_genome`` bumps ``Monster.genome_version`` only on acceptance).
         */
        get: operations["training_history_api_monsters__monster_id__training_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Run
         * @description Stamp the run as saved (durable snapshot marker).
         *
         *     Player position + party already live in durable PG rows (written on every
         *     move / capture), so "saving" stamps ``runs.saved_at`` to mark the run as
         *     resumable. Returns the party size for a quick client-side sanity check.
         */
        post: operations["save_run_api_runs__run_id__save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Return the full durable run state so a session can be rehydrated.
         */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/world": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get World
         * @description Return the seed-deterministic WorldSpecLite for a run.
         *
         *     POIs are produced by the same ``place_pois`` helper the map router uses, so
         *     ``/world`` and ``/map`` always agree for a given seed.
         */
        get: operations["get_world_api_runs__run_id__world_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssistRequest
         * @description The player's rough draft; the lead party monster (its trained genome) rewrites
         *     it into a stronger argument against the current enemy on the live topic.
         *
         *     This is the core of the player-first loop: you argue, your monster makes your
         *     argument better, and training your monster improves the help you get.
         */
        AssistRequest: {
            /**
             * Draft
             * @default
             */
            draft: string;
            /** Skill Id */
            skill_id?: string | null;
        };
        /** AssistResult */
        AssistResult: {
            /** Encounter Id */
            encounter_id: string;
            /** Coach Monster Id */
            coach_monster_id?: string | null;
            /**
             * Suggestions
             * @default []
             */
            suggestions: components["schemas"]["AssistSuggestion"][];
        };
        /** AssistSuggestion */
        AssistSuggestion: {
            /** Improved */
            improved: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /** Skill Id */
            skill_id?: string | null;
            /**
             * Angle
             * @default
             */
            angle: string;
        };
        /** AutoRequest */
        AutoRequest: {
            /**
             * Rounds
             * @default 1
             */
            rounds: number;
        };
        /** CombatantState */
        CombatantState: {
            /** Monster Id */
            monster_id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Role
             * @enum {string}
             */
            role: "party" | "enemy";
            /** Hp */
            hp: number;
            /** Max Hp */
            max_hp: number;
            /** Side */
            side?: ("for" | "against") | null;
        };
        /** CreateEncounterRequest */
        CreateEncounterRequest: {
            /** Run Id */
            run_id: string;
            /** Wild Id */
            wild_id?: string | null;
            /** Enemy Group Id */
            enemy_group_id?: string | null;
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /**
             * Topic
             * @description The debate topic for this entire run
             */
            topic: string;
            /**
             * Player Name
             * @description Display name for the player
             */
            player_name?: string | null;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * Theme
             * @description Theme for this run; battles draw a random topic within it
             */
            theme?: string | null;
        };
        /** EncounterState */
        EncounterState: {
            /** Id */
            id: string;
            /** Run Id */
            run_id: string;
            /** Topic */
            topic: string;
            /**
             * Phase
             * @default intro
             * @enum {string}
             */
            phase: "intro" | "debating" | "capturable" | "won" | "lost";
            /**
             * Turn No
             * @default 0
             */
            turn_no: number;
            /**
             * Combatants
             * @default []
             */
            combatants: components["schemas"]["CombatantState"][];
            /**
             * Transcript
             * @default []
             */
            transcript: components["schemas"]["Utterance"][];
            /**
             * Verdicts
             * @default []
             */
            verdicts: components["schemas"]["JudgeVerdict"][];
        };
        /** GambitList */
        GambitList: {
            /** Monster Id */
            monster_id: string;
            /**
             * Rules
             * @default []
             */
            rules: components["schemas"]["GambitRuleModel"][];
        };
        /** GambitRuleModel */
        GambitRuleModel: {
            /** Id */
            id?: string | null;
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /**
             * Condition
             * @default {}
             */
            condition: {
                [key: string]: unknown;
            };
            /**
             * Action
             * @default {}
             */
            action: {
                [key: string]: unknown;
            };
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Db */
            db: boolean;
            /** Redis */
            redis: boolean;
            /** Gateway */
            gateway: {
                [key: string]: unknown;
            };
        };
        /** JudgeVerdict */
        JudgeVerdict: {
            /** Turn */
            turn: number;
            /** Target */
            target: string;
            /** Score */
            score: number;
            /** Rationale */
            rationale: string;
            /** Damage */
            damage: number;
            /** Why */
            why?: string | null;
            /** Logic */
            logic?: number | null;
            /** Persuasion */
            persuasion?: number | null;
            /** Actor Id */
            actor_id?: string | null;
        };
        /** MapState */
        MapState: {
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Tiles */
            tiles: number[][];
            /** Player X */
            player_x: number;
            /** Player Y */
            player_y: number;
            /**
             * Enemies
             * @default []
             */
            enemies: components["schemas"]["TileEnemy"][];
            /**
             * Pois
             * @default []
             */
            pois: components["schemas"]["POI"][];
        };
        /** MemoryItem */
        MemoryItem: {
            /** Id */
            id: string;
            /** Event Type */
            event_type: string;
            /** Summary */
            summary: string;
            /** Content */
            content: string;
            /** Salience */
            salience: number;
            /** Created At */
            created_at: string;
        };
        /** MemoryQueryResult */
        MemoryQueryResult: {
            /** Monster Id */
            monster_id: string;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["MemoryItem"][];
        };
        /** MonsterSummary */
        MonsterSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Owner */
            owner: string;
            /** Level */
            level: number;
            /** Xp */
            xp: number;
            /** Max Hp */
            max_hp: number;
            /** Evolution Stage */
            evolution_stage: number;
            /**
             * Skills
             * @default []
             */
            skills: unknown[];
            // ---- Gacha-wave additive fields (defaults match the seed catalog) ----
            /** Atk @default 10 */
            atk?: number;
            /** Def @default 10 */
            def?: number;
            /** Mp @default 50 */
            mp?: number;
            /** Max Mp @default 50 */
            max_mp?: number;
            /** Domain @default "GENERAL" */
            domain?: string;
            /** Wiki Url */
            wiki_url?: string | null;
            /** Wiki Hydrated @default false */
            wiki_hydrated?: boolean;
        };
        /**
         * GachaPullRequest
         * @description Pull a persona into the run's party.
         */
        GachaPullRequest: {
            /** Summon Item Id */
            summon_item_id?: string | null;
        };
        /** GachaPullResult */
        GachaPullResult: {
            monster: components["schemas"]["MonsterSummary"];
            /** Persona Key */
            persona_key: string;
            /** Persona Tier */
            persona_tier: string;
        };
        /** SummonItemSummary */
        SummonItemSummary: {
            /** Id */
            id: string;
            /** Run Id */
            run_id: string;
            /** Tier */
            tier: string;
            /** Consumed */
            consumed: boolean;
        };
        /**
         * MemoryRecallResult
         * @description Result of `POST /api/encounters/{eid}/memory-recall` (Wave C ability).
         */
        MemoryRecallResult: {
            /** Encounter Id */
            encounter_id: string;
            /** Coach Monster Id */
            coach_monster_id: string;
            /**
             * Transcript Slice
             * @default []
             */
            transcript_slice: string[];
            /**
             * Highlighted Line
             * @default
             */
            highlighted_line: string;
            /**
             * Counter Text
             * @default
             */
            counter_text: string;
            /**
             * Mp Spent
             * @default 0
             */
            mp_spent: number;
            /**
             * Mp Remaining
             * @default 0
             */
            mp_remaining: number;
            /**
             * Damage
             * @default 0
             */
            damage: number;
        };
        /** MoveRequest */
        MoveRequest: {
            /**
             * Dx
             * @default 0
             */
            dx: number;
            /**
             * Dy
             * @default 0
             */
            dy: number;
        };
        /** MoveResult */
        MoveResult: {
            /** Player X */
            player_x: number;
            /** Player Y */
            player_y: number;
            /** Encounter Id */
            encounter_id?: string | null;
        };
        /**
         * POI
         * @description A point of interest on the map. `kind` is the structural role.
         */
        POI: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "camp" | "town" | "den" | "landmark" | "start" | "goal";
            /** X */
            x: number;
            /** Y */
            y: number;
            /**
             * Name
             * @default
             */
            name: string;
        };
        /**
         * PlayerArgueRequest
         * @description WS-G: a human-typed argument for the player's lead party monster.
         *
         *     `skill_id` is the chosen skill's NAME (skills have no separate id); the engine
         *     resolves it against the lead combatant's skills for the rhetorical type +
         *     damage power multiplier.
         */
        PlayerArgueRequest: {
            /** Text */
            text: string;
            /** Skill Id */
            skill_id?: string | null;
        };
        /** PreferenceBatch */
        PreferenceBatch: {
            /** Job Id */
            job_id: string;
            /** Monster Id */
            monster_id: string;
            /**
             * Variants
             * @default []
             */
            variants: components["schemas"]["PreferenceVariant"][];
        };
        /** PreferenceSubmit */
        PreferenceSubmit: {
            /** Ranking */
            ranking: string[];
        };
        /** PreferenceVariant */
        PreferenceVariant: {
            /** Variant Id */
            variant_id: string;
            /**
             * Transcript
             * @default []
             */
            transcript: components["schemas"]["Utterance"][];
            /**
             * Judge Score
             * @default 0
             */
            judge_score: number;
        };
        /** Region */
        Region: {
            /** Name */
            name: string;
            /**
             * Biome
             * @default plains
             */
            biome: string;
            /** Bounds */
            bounds?: number[] | null;
        };
        /** RestResult */
        RestResult: {
            /** Run Id */
            run_id: string;
            /**
             * Healed
             * @default []
             */
            healed: components["schemas"]["MonsterSummary"][];
            /**
             * Day
             * @default 0
             */
            day: number;
            /**
             * Encounters Since Rest
             * @default 0
             */
            encounters_since_rest: number;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * RunResumeState
         * @description Full durable run state for GET /api/runs/{id} (survives restart).
         *
         *     Extends the in-flight RunState with the captured roster + a resume marker so
         *     the frontend can rehydrate a session after a reload.
         */
        RunResumeState: {
            /** Id */
            id: string;
            /** Debate Topic */
            debate_topic: string;
            /**
             * Player Name
             * @default Player
             */
            player_name: string;
            /** Player X */
            player_x: number;
            /** Player Y */
            player_y: number;
            /** Status */
            status: string;
            /**
             * Party
             * @default []
             */
            party: components["schemas"]["MonsterSummary"][];
            /**
             * Captured
             * @default []
             */
            captured: components["schemas"]["MonsterSummary"][];
            /** Saved At */
            saved_at?: string | null;
            /**
             * Resumable
             * @default false
             */
            resumable: boolean;
        };
        /**
         * RunSaveResult
         * @description Result of POST /api/runs/{id}/save — snapshots run + party to durable PG.
         */
        RunSaveResult: {
            /** Run Id */
            run_id: string;
            /** Saved */
            saved: boolean;
            /** Saved At */
            saved_at: string;
            /**
             * Party Size
             * @default 0
             */
            party_size: number;
        };
        /** RunState */
        RunState: {
            /** Id */
            id: string;
            /** Debate Topic */
            debate_topic: string;
            /** Theme */
            theme?: string | null;
            /** Player X */
            player_x: number;
            /** Player Y */
            player_y: number;
            /** Status */
            status: string;
            /**
             * Party
             * @default []
             */
            party: components["schemas"]["MonsterSummary"][];
        };
        /**
         * Scorecard
         * @description Wave A: measurable before/after training delta against a fixed benchmark.
         *
         *     Units are explicit to avoid the legacy `TrainJob.score_delta` ambiguity:
         *     win_rate_* are 0..1, judge_score_* are 0..100. Computed by the benchmark
         *     harness (deterministic: temp=0 + fixed seed + N-run averaging).
         */
        Scorecard: {
            /**
             * Win Rate Before
             * @default 0
             */
            win_rate_before: number;
            /**
             * Win Rate After
             * @default 0
             */
            win_rate_after: number;
            /**
             * Win Rate Delta
             * @default 0
             */
            win_rate_delta: number;
            /**
             * Judge Score Before
             * @default 0
             */
            judge_score_before: number;
            /**
             * Judge Score After
             * @default 0
             */
            judge_score_after: number;
            /**
             * Judge Score Delta
             * @default 0
             */
            judge_score_delta: number;
            /**
             * Genome Diff
             * @default
             */
            genome_diff: string;
            /**
             * N Benchmark Runs
             * @default 0
             */
            n_benchmark_runs: number;
        };
        /** TileEnemy */
        TileEnemy: {
            /** Id */
            id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /**
             * Sprite
             * @default enemy
             */
            sprite: string;
        };
        /** TrainJob */
        TrainJob: {
            /** Job Id */
            job_id: string;
            /** Monster Id */
            monster_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "gepa" | "grpo";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "awaiting_preference" | "done" | "failed";
            /** Score Delta */
            score_delta?: number | null;
            scorecard?: components["schemas"]["Scorecard"] | null;
        };
        /** TrainRequest */
        TrainRequest: {
            /**
             * Rounds
             * @default 4
             */
            rounds: number;
        };
        /** TrainingHistory */
        TrainingHistory: {
            /** Monster Id */
            monster_id: string;
            /**
             * Entries
             * @default []
             */
            entries: components["schemas"]["TrainingHistoryEntry"][];
        };
        /** TrainingHistoryEntry */
        TrainingHistoryEntry: {
            /** Genome Version */
            genome_version: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "gepa" | "grpo" | "evolution" | "seed";
            /** Created At */
            created_at: string;
            /** Judge Score */
            judge_score?: number | null;
            /** Win Rate */
            win_rate?: number | null;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** TurnResult */
        TurnResult: {
            encounter: components["schemas"]["EncounterState"];
            /**
             * New Utterances
             * @default []
             */
            new_utterances: components["schemas"]["Utterance"][];
            /**
             * New Verdicts
             * @default []
             */
            new_verdicts: components["schemas"]["JudgeVerdict"][];
            /**
             * Capturable Ids
             * @default []
             */
            capturable_ids: string[];
        };
        /** Utterance */
        Utterance: {
            /** Turn */
            turn: number;
            /** Actor Id */
            actor_id: string;
            /**
             * Actor Role
             * @enum {string}
             */
            actor_role: "party" | "enemy" | "judge";
            /** Skill Used */
            skill_used?: string | null;
            /** Text */
            text: string;
            /** Ts */
            ts: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorldSpecLite
         * @description Structured world the FE can render now; the Wave-C generator must emit a
         *     superset of these fields so the frontend contract survives unchanged.
         */
        WorldSpecLite: {
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /**
             * Regions
             * @default []
             */
            regions: components["schemas"]["Region"][];
            /**
             * Pois
             * @default []
             */
            pois: components["schemas"]["POI"][];
            start?: components["schemas"]["POI"] | null;
            goal?: components["schemas"]["POI"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_map_api_runs__run_id__map_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_player_api_runs__run_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rest_api_runs__run_id__rest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_encounter_api_encounters__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEncounterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_encounter_api_encounters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEncounterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_encounter_api_encounters__eid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_turn_api_encounters__eid__turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auto_api_encounters__eid__auto_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    argue_api_encounters__eid__argue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerArgueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assist_api_encounters__eid__assist_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flee_api_encounters__eid__flee_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_monster_api_monsters__monster_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonsterSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gambits_api_monsters__monster_id__gambits_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GambitList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_gambits_api_monsters__monster_id__gambits_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GambitList"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GambitList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memories_api_monsters__monster_id__memories_get: {
        parameters: {
            query?: {
                q?: string | null;
                type?: string | null;
                k?: number;
            };
            header?: never;
            path: {
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryQueryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_party_api_runs__run_id__party_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonsterSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    train_gepa_api_monsters__monster_id__train_gepa_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TrainRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    train_grpo_api_monsters__monster_id__train_grpo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferenceBatch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_preference_api_training__job_id__preference_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferenceSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_training__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    training_history_api_monsters__monster_id__training_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_run_api_runs__run_id__save_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSaveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResumeState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_world_api_runs__run_id__world_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldSpecLite"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
